Create, Validate and GetTicketById for ticket
ELITE-Kinoticketsystem/Backend-KTS pull request #107
Opened 2023-12-31 08:22 UTC by Kieberts

Closes #16

2023-12-31 14:08 UTC, Hajny25 requested changes

2023-12-31 14:08 UTC, Hajny25 commented on src/models/ticketmodels.go
> +// type testStruct struct {
remove commented out code

2023-12-31 18:49 UTC, Kieberts commented on src/models/ticketmodels.go
> +// type testStruct struct {
done

2024-01-04 13:10 UTC, Hajny25 approved these changes

2024-01-04 13:18 UTC, merged