Update ci.yml
ELITE-Kinoticketsystem/Backend-KTS pull request #64
Opened 2023-11-30 15:59 UTC by cll1n

2023-11-30 16:35 UTC, Hajny25 requested changes

2023-11-30 16:35 UTC, Hajny25 commented on .github/workflows/ci.yml
>  name: Continious Integration
continuous

2023-11-30 20:09 UTC, Kieberts commented
Looks good. Not much knowledge

2023-12-01 16:42 UTC, Hajny25 approved these changes

2023-12-02 06:28 UTC, merged